name = "hugo take theme"
license = "MIT"
licenselink = "https://github.com/takeokunn/hugo-take-theme/blob/master/LICENSE"
description = ""
homepage = "https://github.com/takeokunn/hugo-take-theme"
tags = []
features = ["blog", "sass", "dark"]
min_version = "0.87.0"

[author]
  name = "takeokunn"
  homepage = "https://github.com/takeokunn/hugo-take-theme"
