name: CI

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache node_modules
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - name: Install npm
        run: npm ci
      - name: Run textlint
        run: npm run lint:stylelint
      - name: Run secretlint
        run: npm run lint:secretlint
